import { afterEach, expect, it, vi } from 'vitest'
const mocks = vi.hoisted(() => ({ createClient: vi.fn(), resolveOwnedProjectResult: vi.fn() }))
vi.mock('@/lib/supabase/server', () => ({ createClient: mocks.createClient }))
vi.mock('@/lib/academic-suite/repositories/projects', () => ({ resolveOwnedProjectResult: mocks.resolveOwnedProjectResult }))
afterEach(() => vi.clearAllMocks())
const row = { material_id: '11111111-1111-4111-8111-111111111111', manifest_id: '22222222-2222-4222-8222-222222222222', created_at: '2026-09-07T12:00:00Z', expires_at: '2026-09-10T12:00:00Z', cleanup: 'pending', extractedText: 'must not be returned' }
it('lists only owned privacy metadata without an active Pass or Storage reads', async () => {
  const rpc = vi.fn().mockResolvedValue({ data: [row] })
  mocks.createClient.mockResolvedValue({ auth: { getUser: async () => ({ data: { user: { id: 'owner' } } }) }, rpc })
  mocks.resolveOwnedProjectResult.mockResolvedValue({ ok: true, value: { projectId: 'owned-project' } })
  const { GET } = await import('./privacy/route')
  const response = await GET(new Request('http://localhost/api/materials/privacy?projectId=owned-project'))
  expect(response.status).toBe(200)
  expect(response.headers.get('cache-control')).toBe('private, no-store')
  const body = await response.json()
  expect(body.materials).toEqual([{ materialId: row.material_id, manifestId: row.manifest_id, createdAt: row.created_at, expiresAt: row.expires_at, cleanup: 'pending' }])
  expect(JSON.stringify(body)).not.toContain('must not be returned')
  expect(rpc).toHaveBeenCalledWith('list_material_payload_privacy', { p_user_id: 'owner', p_project_id: 'owned-project', p_after: null })
})
it('does not query another owner project', async () => {
  const rpc = vi.fn()
  mocks.createClient.mockResolvedValue({ auth: { getUser: async () => ({ data: { user: { id: 'owner' } } }) }, rpc })
  mocks.resolveOwnedProjectResult.mockResolvedValue({ ok: true, value: null })
  const { GET } = await import('./privacy/route')
  expect((await GET(new Request('http://localhost/api/materials/privacy?projectId=foreign'))).status).toBe(404)
  expect(rpc).not.toHaveBeenCalled()
})
it('rejects malformed pagination before querying canonical metadata', async () => {
  const rpc = vi.fn()
  mocks.createClient.mockResolvedValue({ auth: { getUser: async () => ({ data: { user: { id: 'owner' } } }) }, rpc })
  const { GET } = await import('./privacy/route')
  expect((await GET(new Request('http://localhost/api/materials/privacy?projectId=owned-project&after=../bad'))).status).toBe(400)
  expect(rpc).not.toHaveBeenCalled()
})
it('returns a bounded page and a cursor that does not skip the first unseen item', async () => {
  const rows = Array.from({ length: 101 }, (_, index) => ({ ...row, manifest_id: `22222222-2222-4222-8222-${String(index).padStart(12, '0')}` }))
  const rpc = vi.fn().mockResolvedValue({ data: rows })
  mocks.createClient.mockResolvedValue({ auth: { getUser: async () => ({ data: { user: { id: 'owner' } } }) }, rpc })
  mocks.resolveOwnedProjectResult.mockResolvedValue({ ok: true, value: { projectId: 'owned-project' } })
  const { GET } = await import('./privacy/route')
  const body = await (await GET(new Request('http://localhost/api/materials/privacy?projectId=owned-project'))).json()
  expect(body.materials).toHaveLength(100)
  expect(body.nextCursor).toBe(rows[99].manifest_id)
  expect(body.materials.some(item => item.manifestId === rows[100].manifest_id)).toBe(false)
})
